version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform…"
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip -o terraform_1.5.0_linux_amd64.zip -d /tmp
      - mv -f /tmp/terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform

  pre_build:
    commands:
     - echo "## Listing root of CODEBUILD_SRC_DIR## "
     - ls -R .
     - echo "-----------------------------"
  build:
    commands:
    - terraform destroy -auto-approve tfplan
