version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      # Remove any old terraform binary first, then unzip with -o to overwrite without prompt
      - rm -f terraform
      - unzip -o terraform_1.5.0_linux_amd64.zip
      - mv -f terraform /usr/local/bin/
  build:
    commands:
      - cd terraform
      - terraform fmt -check
      - terraform init -backend-config="bucket=sinmisworld-ult-cloud-terraform-state" -backend-config="key=state.tfstate"
      - terraform validate
      - terraform plan -out=tfplan
artifacts:
  files:
    - terraform/tfplan
