version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
            # Unzip into /tmp to avoid clobbering the terraform/ folder in our repo
      - unzip -o terraform_1.5.0_linux_amd64.zip -d /tmp
      - mv -f /tmp/terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
  build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - echo "Formatting Terraform code..."
      - terraform fmt
      - terraform init -backend-config="bucket=sinmisworld-ult-cloud-terraform-state" -backend-config="key=state.tfstate"
      - terraform validate
      - echo "Planning with DB_USERNAME=$DB_USERNAME"
      - terraform plan -var "db_username=${DB_USERNAME}" -var "db_password=${DB_PASSWORD}" -out=tfplan

  post_build:
    commands:
      - echo "== Contents of terraform folder =="
      - ls -la terraform
      - echo "== Listing root folder =="
      - ls -R .
artifacts:
  files:
    - tfplan
